### PR TITLE
FIx and updates

### PR DESCRIPTION
**Pull request by JeffBeckLim**

### CODE REVIEW

**Comment by FN-FAL113** [comment]
image
pa remove ng admin dito

**Review by FN-FAL113 — CHANGES_REQUESTED** [review]
May admin verification na to? like pag ka register, admin verification ang gagamitin

**Comment by FN-FAL113** [comment]
pa update din ng profile photo upload na di required

**Comment by FN-FAL113** [comment]
tsaka pala men yung changes sa migrations or db fields sa positions, solely for positions lng dpat naka store dun walang employee_id

**Comment by FN-FAL113** [comment]
same sa roles table dpt wala din dun employee_id, masisira yung database design natin nyan, mostly kukunin nyo yang data through relationships gamit ang laravel eloquent or kung db facade (raw SQL, much harder)

**Comment by FN-FAL113** [comment]
also same sa departments, gamitan nyo n lng ng model relationships para d kayo mahirapan

**Comment by Teds30** [comment]
add narin kayo ng factory an seeder para sa roles

**Pull request merged**
